### ISSUE TITLE
Cannot end/close the stream

### ISSUE THREAD

**Issue by roccomuso** [wankdanker/node-datagram-stream#4]
I've not being able to pipe something into a buffer using [concat-stream](https://www.npmjs.com/package/concat-stream). I guess because there's not a clear way to gracefully end the stream. Neither with [destroy](https://www.npmjs.com/package/destroy).

Any hints?

**Comment by roccomuso** [comment]
Or you can listen for the `close` event and emit `end` on the socket.

**Comment by wankdanker** [comment]
If your patch which has been merged fixes this issue, please close this issue. Thank you!

**Comment by roccomuso** [comment]
@wankdanker Yes. Thank you.
